//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonents
    {
        public string НомерАбонента { get; set; }
        public string ФИО { get; set; }
        public string Пол { get; set; }
        public Nullable<System.DateTime> ДатаРождения { get; set; }
        public string НомерТелефона { get; set; }
        public string ЭлектроннаяПочта { get; set; }
        public string АдресПрописки { get; set; }
        public string АдресПроживания { get; set; }
        public string СерияИНомерПаспорта { get; set; }
        public string КодПодразделения { get; set; }
        public string КемВыдан { get; set; }
        public Nullable<System.DateTime> ДатаВыдачиПаспорта { get; set; }
        public string НомерДоговора { get; set; }
        public Nullable<System.DateTime> ДатаЗаключенияДоговора { get; set; }
        public string ТипДоговора { get; set; }
        public string ПричинаРасторженияДоговора { get; set; }
        public string ЛицевойСчет { get; set; }
        public string Услуга1 { get; set; }
        public string Услуга2 { get; set; }
        public string Услуга3 { get; set; }
        public Nullable<System.DateTime> ДатаРасторженияДоговора { get; set; }
        public string СерийныйНомерОборудования { get; set; }
    }
}
