//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM
    {
        public int Id { get; set; }
        public string НомерЗаявки { get; set; }
        public Nullable<System.DateTime> ДатаСоздания { get; set; }
        public string ЛС { get; set; }
        public string Услуга { get; set; }
        public string ВидУслуги { get; set; }
        public string ТипУслуги { get; set; }
        public string Статус { get; set; }
        public string ТипОборудования { get; set; }
        public string ОписаниеПроблемы { get; set; }
        public Nullable<System.DateTime> ДатаЗакрытия { get; set; }
        public string ТипПроблема { get; set; }
    }
}
