//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CallCentersEntities2 : DbContext
    {
        private static CallCentersEntities2 _context;

        public CallCentersEntities2()
            : base("name=CallCentersEntities2")
        {
        }
        public static  CallCentersEntities2 GetContext()
        {
            _context = new CallCentersEntities2();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonents> Abonents { get; set; }
        public virtual DbSet<CRM> CRM { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Transponder> Transponder { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<usersRole> usersRole { get; set; }
    }
}
