//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transponder
    {
        public int Id { get; set; }
        public string СерийныйНомер { get; set; }
        public string Название { get; set; }
        public Nullable<decimal> Частота { get; set; }
        public Nullable<decimal> КоэффициентЗатухания { get; set; }
        public string ТехнологияПередачиДанных { get; set; }
        public string Расположение { get; set; }
    }
}
