//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelecomТeoSvyaz.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public Nullable<int> number { get; set; }
        public string password { get; set; }
        public Nullable<int> code { get; set; }
        public Nullable<int> id_role { get; set; }
    
        public virtual usersRole usersRole { get; set; }
    }
}
